// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5O-2jlLlYcKYGxMY5bi8n0_mYBQ4NKu4',
    appId: '1:841433483744:web:d95945cffe4a848bdd8385',
    messagingSenderId: '841433483744',
    projectId: 'sharebill-96be0',
    authDomain: 'sharebill-96be0.firebaseapp.com',
    storageBucket: 'sharebill-96be0.appspot.com',
    measurementId: 'G-KE1NKRSNZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiu8TNpUbGoNd_ZZ5tmxiTzYBXflsn83g',
    appId: '1:841433483744:android:2723e3ea9e5e6f75dd8385',
    messagingSenderId: '841433483744',
    projectId: 'sharebill-96be0',
    storageBucket: 'sharebill-96be0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiSwVlepP8C1ULNmE5M99As30QBAalYqE',
    appId: '1:841433483744:ios:08b6e7935617b13ddd8385',
    messagingSenderId: '841433483744',
    projectId: 'sharebill-96be0',
    storageBucket: 'sharebill-96be0.appspot.com',
    iosClientId: '841433483744-5rrq2auaa7ip3ht94hc8b0igco9fvj16.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareBill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiSwVlepP8C1ULNmE5M99As30QBAalYqE',
    appId: '1:841433483744:ios:08b6e7935617b13ddd8385',
    messagingSenderId: '841433483744',
    projectId: 'sharebill-96be0',
    storageBucket: 'sharebill-96be0.appspot.com',
    iosClientId: '841433483744-5rrq2auaa7ip3ht94hc8b0igco9fvj16.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareBill',
  );
}
